sudo: required
dist: trusty
language: python
matrix:
    include:
        - python: 3.5
        - python: 3.4
        - python: 2.7
install:
    - ci/.travis_install.sh
script:
    - ci/.travis_test.sh
notifications:
    email:
      recipients:
          - mail@sebastianraschka.com
    on_success: always
    on_failure: always
